jet-fuel/config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  resources :urls
  get "/:short_url" => "urls#redirect", as: "short_url_redirect"

  namespace :api do
    namespace :v1 do
      root "welcome#index"
      resources :urls
      get "/:short_url" => "urls#redirect", as: "short_url_redirect"
    end
  end
end

jet-fuel/app/models/url.rb
class Url < ActiveRecord::Base
  before_validation :shorten_url
  validates :full_url, presence: true, uniqueness: true,
    format: URI::regexp(%w(http https))
  validates :short_url, presence: true, uniqueness: true

  def shorten_url
    self.short_url = Time.new.strftime("%H%M%S")
  end

  def up_visit_count
    self.visit_count += 1
    save
  end
end

jet-fuel/app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

jet-fuel/app/controllers/api/v1/urls_controller.rb
class Api::V1::UrlsController < ApplicationController
  respond_to :json, :xml

  def create
    @url = Url.new(url_params)
    if @url.save
      respond_with @url
    else
      respond with "Error, did not create"
    end
  end

  def show
    respond_with Url.find(params[:id])
  end

  def redirect
    @url = Url.find_by(short_url: params[:short_url])
    @url.up_visit_count
    respond_with @url.full_url
  end

  private

  def url_params
    params.require(:url).permit(:full_url)
  end
end

jet-fuel/app/controllers/api/v1/welcome_controller.rb
class Api::V1::WelcomeController < ApplicationController
  respond_to :xml, :json

  def index
    respond_with @urls = Url.all
  end
end

jet-fuel/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

jet-fuel/app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def create
    url = Url.new(url_params)
    if url.save
      redirect_to url_path(url)
    else
      flash[:errors] = "Invalid URL"
      redirect_to root_path
    end
  end

  def show
    @url = Url.find(params[:id])
  end

  def redirect
    @url = Url.find_by(short_url: params[:short_url])
    @url.up_visit_count
    redirect_to @url.full_url
  end

  private

  def url_params
    params.require(:url).permit(:full_url)
  end
end

jet-fuel/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @urls = Url.all
    @url = Url.new
  end
end

jet-fuel/app/helpers/application_helper.rb
module ApplicationHelper
end

jet-fuel/app/helpers/urls_helper.rb
module UrlsHelper
end

jet-fuel/app/helpers/welcome_helper.rb
module WelcomeHelper
end

jet-fuel/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JetFuel</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |name, message| %>
  <%= message%>
<% end %>

<%= yield %>

</body>
</html>

jet-fuel/app/views/urls/show.html.erb
<div class="text-center">
  <h1> Your URL has been shortened!</h1>
    <h3> Original Url: <%= @url.full_url %></h3>
    <h3> Shortened url:
      <%= link_to short_url_redirect_path(short_url: @url.short_url),
                  short_url_redirect_path(short_url: @url.short_url) %>
    </h3>
    <h1> <%= link_to "Home", root_path %><h1>
</div>

jet-fuel/app/views/welcome/index.html.erb
<div class="row text-center">
  <h1> Welcome to Jet Fuel </h1>
  <h3> The fastest way to short URLs </h3>
</div>

<div class="row text_center col-md-push-3 col-md-6 url-input" >
  <%= bootstrap_form_for(@url) do |f| %>
  <%= f.text_field :full_url %>
  <%= f.submit "Make it shorter!" %>
  <% end %>
</div>

<div class="data-table row text-center col-md-12">
  <table id="urls" class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th> Full URL Title </th>
        <th> Shortented URL </th>
        <th> Time created </th>
        <th> Popularity</th>
      </tr>
    </thead>
    <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%=url.full_url  %></td>
        <td><%= link_to "#{url.short_url}",
        short_url_redirect_path(short_url: url.short_url),
        :target => "_blank" %></td>
        <td><%=url.created_at.strftime("%m/%d/%Y at %I:%M%p")  %></td>
        <td><%= url.visit_count  %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
</div>